### ISSUE TITLE
XS::Parse::Sublike ABI v3 is now deprecated

### ISSUE THREAD

**Issue by eserte** [FGasper/p5-Promise-ES6#12]
t/async_await_additional.t started to fail on some of my smoker systems:
```
#   Failed test 'Test::FailWarnings should catch no warnings'
#   at t/async_await_additional.t line 47.
# Warning was 'XS::Parse::Sublike ABI v3 is now deprecated; the caller should be rebuilt to use v4 at t/async_await_additional.t line 47.'

#   Failed test 'Test::FailWarnings should catch no warnings'
#   at t/async_await_additional.t line 53.
# Warning was 'XS::Parse::Sublike ABI v3 is now deprecated; the caller should be rebuilt to use v4 at t/async_await_additional.t line 53.'
# Looks like you planned 3 tests but ran 5.
# Looks like you failed 2 tests of 5 run.
t/async_await_additional.t ........ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests 
```

**Comment by FGasper** [comment]
Thanks!

I’d seen this sometime back but neglected to push the fix. That’s now done, so I’m closing.

**Comment by eserte** [comment]
@FGasper Well, I don't see a change in 0.25...

**Comment by FGasper** [comment]
@eserte Are your failures on CPAN Testers? Which version of Future::AsyncAwait is installed?

**Comment by eserte** [comment]
I looked into one of the affected perls, and there is Future::AsyncAwait 0.54 installed, the latest.

**Comment by eserte** [comment]
I see the warning also with the following oneliner:
```
$ perl5.30.2 -MFuture::AsyncAwait -e 'async sub bla { }'            
XS::Parse::Sublike ABI v3 is now deprecated; the caller should be rebuilt to use v4 at -e line 1.
```
Only on some of my smokers: Ubuntu 20.04, CentOS7 and some older freebsd systems.

**Comment by eserte** [comment]
Rebuilding Future::AsyncAwait seems to help. But this does not feel right to me... maybe the XS::Parse::Sublike and/or Future::AsyncAwait author can tell something about it.
